### PR TITLE
Remove caching support in HighVoltage

### PR DESCRIPTION
**Pull request by dgalarza**
Page caching was deprecated in fac899f. In preparation to move towards a 3.0 release with
Rails 5.0 support, we are removing built in caching support. Specifically the `actionpack-action_caching` and `actionpack-page_caching` do not support Rails 5 which makes it harder for us to push forward.

### CODE REVIEW

**Comment by bernerdschaefer** [comment]
LGTM

Is there some other form of caching we should recommend instead?

**Comment by dgalarza** [comment]
Good question @bernerdschaefer. Perhaps instead of removing the section in the README about caching altogether, we keep the links to `actionpack-page_caching` for reference.

**Comment by dgalarza** [comment]
Updated the README to restore our notes on caching and linking to the Rails guides. WDUT @bernerdschaefer?

**Comment by bernerdschaefer** [comment]
:+1:

**Pull request merged**
