### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by dgalarza**

### CODE REVIEW

**Comment by tute** [comment]
This looks great. Do we need upgrade instructions?

**Comment by mike-burns** [comment]
1. Yay! LGTM.  
2. Why 3.0.0 instead of 2.5.0?

**Comment by tute** [comment]
> Why 3.0.0 instead of 2.5.0?

Is https://github.com/thoughtbot/high_voltage/pull/221 backwards incompatible?

**Comment by mike-burns** [comment]
Aha, it probably is. 3.0.0 it is!

**Comment by dgalarza** [comment]
> Is #221 backwards incompatible?
Correct!

**Comment by dgalarza** [comment]
> This looks great. Do we need upgrade instructions?

I don't think we do. The README was previously updated on the removal of caching with instructions on how to move forward if needed. I think that will suffice.

Thanks @tute / @mike-burns

**Pull request merged**
