### PR TITLE
Test against Rails 5.1.x

### PR DESCRIPTION
**Pull request by dgalarza**
Removes `headers` call in HTTPMethodShim since it is not supported as a
keyword argument anymore. We weren't making use of it as it is.

### CODE REVIEW

**Comment by mike-burns** [comment]
Should we `**_unused` as the last argument, or something? Like, we don't care what else people pass in different versions of Rails, so let's let them pass whatever?

Or does this already work fine with extra kw args being passed?

**Comment by dgalarza** [comment]
The shim is in place since Rails 5 deprecated positional arguments over keyword arguments.

So instead of: `get :show, id: "foo"` we need to do `get :show, params: { id: "foo" }`. Right now in our internal tests we aren't using any of the other argument options for a controller spec such as flash notice or session variables though this could change in the future.

I think it might be more useful to throw an error if additional args are passed to the shim method in the future to point out that something needs to be done in order for the test to work as expected under Rails 5.x as opposed to just silently grabbing any additional arguments and letting them fall through.

**Comment by mike-burns** [comment]
Cool. LGTM as is, but I do like the idea of having this raise sooner.

**Comment by dgalarza** [comment]
> but I do like the idea of having this raise sooner.

I'm curious about this. Are you thinking something like:

```ruby
def get(path, params = nil, *args)
  if args.any?
    raise ArgumentError, "Unsupported argument provided to shim"
   else
     super(params: params)
   end
end
```

**Comment by mike-burns** [comment]
Yes, something like that.

It exists for us so that we can get alerted to Rails changes sooner. So even:

```ruby
raise ArgumentError, "Rails passed unexpected arguments to our shim: #{args.inspect}"
```

**Comment by dgalarza** [comment]
I like it! 👍

**Comment by mike-burns** [comment]
LGTM!

**Comment by dgalarza** [comment]
Thanks @mike-burns!

**Pull request merged**
