### PR TITLE
EOL Rails 5.0 and Rails 5.1

### PR DESCRIPTION
**Pull request by keegnotrub**
Being we no longer run automated tests against these versions of Rails this removes support for them in the gem.

Dropping support for Rails 5.0 also allows us to bump `rspec-rails` to be using `4.0.0` at minimum.

### CODE REVIEW

**Review by sarahraqueld — APPROVED** [review]
LGTM

**Review by MatheusRich — APPROVED** [review]
Should we drop support for 5.x altogether?

**Comment by keegnotrub** [comment]
Good question on dropping 5.2. We [dropped 4.2](https://github.com/thoughtbot/high_voltage/commit/ecf3c53d93edb7044cbc948c8f2538ef81138ec5) in 2019 (two years after it's security releases stopped). Not that we'd have to go by that, but if we did, it looks like we'd keep 5.2 around until Summer of 2024?

**Comment by MatheusRich** [comment]
@keegnotrub sounds good. ty!

**Pull request merged**
